# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Dan Curtis
email: dgcurtis4@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my blog! A place for me to play around with maths, coding and data topics that interest me, amongst other things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dan-curtis.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  dan-curtis

# Fields that minima uses but are not defaulted
# author is default for posts, atom feed and footer
author: Dan Curtis
linkedin_username: dgcurtis4
# header pages overwrites default alphabetical header listing of all pages
header_pages:
  - blog-maths/index.md
  - blog-code/index.md
  - pages/about.md
# below sets utterances comments to True by default
# set comments: false on individual posts to override
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      comments: true
# repository for utterances to find the issues
repository: dan-curtis/dan-curtis.github.io
# utterances widget
comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"
    label: "comment" # Optional - must be existing label.

# New fields not defaulted by jekyll-new with the minima theme
# Add a copyright, sumbol and year added automatically
# copyright: Company Name Inc.
# copyright: Company Name ltd
# title-logo is a new field that when populated displays a logo
# ideally the image should be 50px high and take up minimal horizontal space
# title-logo: /images/my-logo.png (jpeg etc)
# title-logo: /assets/images/title-logo.png
title-logo: /assets/images/logo-light.svg
favicon: /assets/images/favicon-dark.svg

# Build settings
# Removed minima theme as it is now a regular theme.
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
